#custom property(절대경로 Apsolute Path)
file:
  directory: D:/LJM/GeenGramVer1/


#mybatis setting
mybatis:
  mapper-locations: xml/**/*.xml

# Base URL setting
#server:
#  servlet:
#    context-path: /api


spring:
  application:
    name: GreenGramVer1

  # DB setting
  datasource:
    url: jdbc:mariadb://localhost/greengram_ver1
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 15MB


springdoc:
  swagger-ui:
    defaultModelExpandDepth: 10
    display-request-duration: true
    operations-shorter: method
    path: /swagger
  cache:
    disabled: true
